name: Build and Test
on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install bun
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run tests
        steps:
          - run: bun test
